name: Update the tracy-client-sys crate

on:
  workflow_dispatch:
  schedule:
    - cron: '37 0/6 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - run: rustup install stable --profile=minimal
      - run: rustup default stable
      - run: cargo install bindgen-cli
      - run: sudo apt install -y jq curl
      - run: bash make_sys.sh
        id: make_sys
      - run: git diff
      - if: ${{ steps.make_sys.outputs.tracy-changed }}
        uses: tibdex/github-app-token@36464acb844fc53b9b8b2401da68844f6b05ebb0
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - if: ${{ steps.make_sys.outputs.tracy-changed }}
        name: Create Pull Request
        uses: peter-evans/create-pull-request@d9d6fd980e1e0904e8e4dce3f0992640091bde37
        with:
          title: "Update tracy client bindings to ${{ steps.make_sys.outputs.tracy-tag }}"
          body: ''
          delete-branch: true
          token: ${{ steps.generate-token.outputs.token }}
          base: main
